// AUTO-GENERATED — Manual equivalent of Unity's Input System code gen.
// Source: InputSystem_Actions.inputactions
// Actions exposed: Move, Look, Attack, Interact, Crouch, Jump, Previous, Next, Sprint
// Namemap: Player map and UI map.

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Manually written equivalent of the Unity-generated InputSystem_Actions wrapper.
/// Generated by Unity Input System from InputSystem_Actions.inputactions.
/// </summary>
public class InputSystem_Actions : IInputActionCollection2, IDisposable
{
    private InputActionAsset _asset;

    public InputActionAsset asset => _asset;

    // ─── Action Maps ──────────────────────────────────────────────────────
    private InputActionMap _playerMap;
    private InputActionMap _uiMap;

    // ─── Player Actions ───────────────────────────────────────────────────
    private InputAction _moveAction;
    private InputAction _lookAction;
    private InputAction _attackAction;
    private InputAction _interactAction;
    private InputAction _crouchAction;
    private InputAction _jumpAction;
    private InputAction _previousAction;
    private InputAction _nextAction;
    private InputAction _sprintAction;

    public PlayerActionsMap Player { get; private set; }
    public UIActionsMap UI { get; private set; }

    public InputSystem_Actions()
    {
        _asset = InputActionAsset.FromJson(ProjectZ.Player.InputSystem_ActionsJson.JSON);

        _playerMap = _asset.FindActionMap("Player", throwIfNotFound: true);
        _uiMap     = _asset.FindActionMap("UI",     throwIfNotFound: true);

        _moveAction     = _playerMap.FindAction("Move",     throwIfNotFound: true);
        _lookAction     = _playerMap.FindAction("Look",     throwIfNotFound: true);
        _attackAction   = _playerMap.FindAction("Attack",   throwIfNotFound: true);
        _interactAction = _playerMap.FindAction("Interact", throwIfNotFound: true);
        _crouchAction   = _playerMap.FindAction("Crouch",   throwIfNotFound: true);
        _jumpAction     = _playerMap.FindAction("Jump",     throwIfNotFound: true);
        _previousAction = _playerMap.FindAction("Previous", throwIfNotFound: true);
        _nextAction     = _playerMap.FindAction("Next",     throwIfNotFound: true);
        _sprintAction   = _playerMap.FindAction("Sprint",   throwIfNotFound: true);

        Player = new PlayerActionsMap(_moveAction, _lookAction, _attackAction, _interactAction,
                                      _crouchAction, _jumpAction, _previousAction, _nextAction, _sprintAction);
        UI = new UIActionsMap(_uiMap);
    }

    public void Enable()  => _asset.Enable();
    public void Disable() => _asset.Disable();
    public void Dispose() { if (_asset != null) { UnityEngine.Object.Destroy(_asset); _asset = null; } }

    // IInputActionCollection2
    public InputBinding? bindingMask
    {
        get => _asset.bindingMask;
        set => _asset.bindingMask = value;
    }
    public ReadOnlyArray<InputDevice>? devices
    {
        get => _asset.devices;
        set => _asset.devices = value;
    }
    public ReadOnlyArray<InputControlScheme> controlSchemes => _asset.controlSchemes;

    // IInputActionCollection2 — additional required members
    public IEnumerable<InputBinding> bindings => _asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        => _asset.FindAction(actionNameOrId, throwIfNotFound);

    public int FindBinding(InputBinding bindingMask, out InputAction action)
        => _asset.FindBinding(bindingMask, out action);

    public bool Contains(InputAction action) => _asset.Contains(action);
    public IEnumerator<InputAction> GetEnumerator() => _asset.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();


    // ─── Player Map Wrapper ───────────────────────────────────────────────
    public struct PlayerActionsMap
    {
        public InputAction Move     { get; }
        public InputAction Look     { get; }
        public InputAction Attack   { get; }
        public InputAction Interact { get; }
        public InputAction Crouch   { get; }
        public InputAction Jump     { get; }
        public InputAction Previous { get; }
        public InputAction Next     { get; }
        public InputAction Sprint   { get; }

        internal PlayerActionsMap(InputAction move, InputAction look, InputAction attack,
            InputAction interact, InputAction crouch, InputAction jump,
            InputAction previous, InputAction next, InputAction sprint)
        {
            Move     = move;
            Look     = look;
            Attack   = attack;
            Interact = interact;
            Crouch   = crouch;
            Jump     = jump;
            Previous = previous;
            Next     = next;
            Sprint   = sprint;
        }
    }

    // ─── UI Map Wrapper ───────────────────────────────────────────────────
    public struct UIActionsMap
    {
        private readonly InputActionMap _map;
        public InputAction Navigate           { get; }
        public InputAction Submit             { get; }
        public InputAction Cancel             { get; }
        public InputAction Point              { get; }
        public InputAction Click              { get; }
        public InputAction ScrollWheel        { get; }
        public InputAction MiddleClick        { get; }
        public InputAction RightClick         { get; }
        public InputAction TrackedDevicePosition    { get; }
        public InputAction TrackedDeviceOrientation { get; }

        internal UIActionsMap(InputActionMap map)
        {
            _map = map;
            Navigate                 = map.FindAction("Navigate",                   throwIfNotFound: true);
            Submit                   = map.FindAction("Submit",                     throwIfNotFound: true);
            Cancel                   = map.FindAction("Cancel",                     throwIfNotFound: true);
            Point                    = map.FindAction("Point",                      throwIfNotFound: true);
            Click                    = map.FindAction("Click",                      throwIfNotFound: true);
            ScrollWheel              = map.FindAction("ScrollWheel",                throwIfNotFound: true);
            MiddleClick              = map.FindAction("MiddleClick",                throwIfNotFound: true);
            RightClick               = map.FindAction("RightClick",                 throwIfNotFound: true);
            TrackedDevicePosition    = map.FindAction("TrackedDevicePosition",      throwIfNotFound: true);
            TrackedDeviceOrientation = map.FindAction("TrackedDeviceOrientation",   throwIfNotFound: true);
        }
    }
}

namespace ProjectZ.Player
{
    /// <summary>
    /// Holds the embedded JSON for InputSystem_Actions so the asset can be loaded at runtime
    /// without needing the .inputactions file to be in Resources/.
    /// </summary>
    internal static class InputSystem_ActionsJson
    {
        internal const string JSON =
            @"{
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""df70fa95-8a34-4494-b137-73ab6b9c7d37"",
            ""actions"": [
                { ""name"": ""Move"",     ""type"": ""Value"",  ""id"": ""351f2ccd-1f9f-44bf-9bec-d62ac5c5f408"", ""expectedControlType"": ""Vector2"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": true },
                { ""name"": ""Look"",     ""type"": ""Value"",  ""id"": ""6b444451-8a00-4d00-a97e-f47457f736a8"", ""expectedControlType"": ""Vector2"", ""processors"": """", ""interactions"": """", ""initialStateCheck"": true },
                { ""name"": ""Attack"",   ""type"": ""Button"", ""id"": ""6c2ab1b8-8984-453a-af3d-a3c78ae1679a"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Interact"", ""type"": ""Button"", ""id"": ""852140f2-7766-474d-8707-702459ba45f3"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": ""Hold"", ""initialStateCheck"": false },
                { ""name"": ""Crouch"",   ""type"": ""Button"", ""id"": ""27c5f898-bc57-4ee1-8800-db469aca5fe3"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Jump"",     ""type"": ""Button"", ""id"": ""f1ba0d36-48eb-4cd5-b651-1c94a6531f70"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Previous"", ""type"": ""Button"", ""id"": ""2776c80d-3c14-4091-8c56-d04ced07a2b0"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Next"",     ""type"": ""Button"", ""id"": ""b7230bb6-fc9b-4f52-8b25-f5e19cb2c2ba"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Sprint"",   ""type"": ""Button"", ""id"": ""641cd816-40e6-41b4-8c3d-04687c349290"", ""expectedControlType"": ""Button"",  ""processors"": """", ""interactions"": """", ""initialStateCheck"": false }
            ],
            ""bindings"": [
                { ""name"": """", ""id"": ""978bfe49-cc26-4a3d-ab7b-7d7a29327403"", ""path"": ""<Gamepad>/leftStick"", ""groups"": "";Gamepad"",          ""action"": ""Move"",     ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": ""WASD"", ""id"": ""00ca640b-d935-4593-8157-c05846ea39b3"", ""path"": ""Dpad"",  ""groups"": """",  ""action"": ""Move"",  ""isComposite"": true, ""isPartOfComposite"": false },
                { ""name"": ""up"",   ""id"": ""e2062cb9-1b15-46a2-838c-2f8d72a0bdd9"", ""path"": ""<Keyboard>/w"", ""groups"": ""; Keyboard&Mouse"", ""action"": ""Move"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""down"", ""id"": ""320bffee-a40b-4347-ac70-c210eb8bc73a"", ""path"": ""<Keyboard>/s"", ""groups"": ""; Keyboard&Mouse"", ""action"": ""Move"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""left"", ""id"": ""d2581a9b-1d11-4566-b27d-b92aff5fabbc"", ""path"": ""<Keyboard>/a"", ""groups"": ""; Keyboard&Mouse"", ""action"": ""Move"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": ""right"",""id"": ""fcfe95b8-67b9-4526-84b5-5d0bc98d6400"", ""path"": ""<Keyboard>/d"", ""groups"": ""; Keyboard&Mouse"", ""action"": ""Move"", ""isComposite"": false, ""isPartOfComposite"": true },
                { ""name"": """", ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"", ""path"": ""<Gamepad>/rightStick"", ""groups"": ""; Gamepad"", ""action"": ""Look"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""8c8e490b-c610-4785-884f-f04217b23ca4"", ""path"": ""<Pointer>/delta"", ""groups"": ""; Keyboard&Mouse;Touch"", ""action"": ""Look"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""143bb1cd-cc10-4eca-a2f0-a3664166fe91"", ""path"": ""<Gamepad>/buttonWest"", ""groups"": ""; Gamepad"", ""action"": ""Attack"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""05f6913d-c316-48b2-a6bb-e225f14c7960"", ""path"": ""<Mouse>/leftButton"", ""groups"": ""; Keyboard&Mouse"", ""action"": ""Attack"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""f2e9ba44-c423-42a7-ad56-f20975884794"", ""path"": ""<Keyboard>/leftShift"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Sprint"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""eb40bb66-4559-4dfa-9a2f-820438abb426"", ""path"": ""<Keyboard>/space"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Jump"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""36e52cba-0905-478e-a818-f4bfcb9f3b9a"", ""path"": ""<Keyboard>/c"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Crouch"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""1534dc16-a6aa-499d-9c3a-22b47347b52a"", ""path"": ""<Keyboard>/1"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Previous"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""cbac6039-9c09-46a1-b5f2-4e5124ccb5ed"", ""path"": ""<Keyboard>/2"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Next"", ""isComposite"": false, ""isPartOfComposite"": false },
                { ""name"": """", ""id"": ""1c04ea5f-b012-41d1-a6f7-02e963b52893"", ""path"": ""<Keyboard>/e"", ""groups"": ""Keyboard&Mouse"", ""action"": ""Interact"", ""isComposite"": false, ""isPartOfComposite"": false }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""272f6d14-89ba-496f-b7ff-215263d3219f"",
            ""actions"": [
                { ""name"": ""Navigate"",                 ""type"": ""PassThrough"", ""id"": ""c95b2375-e6d9-4b88-9c4c-c5e76515df4b"", ""expectedControlType"": ""Vector2"",   ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Submit"",                   ""type"": ""Button"",      ""id"": ""7607c7b6-cd76-4816-beef-bd0341cfe950"", ""expectedControlType"": ""Button"",    ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Cancel"",                   ""type"": ""Button"",      ""id"": ""15cef263-9014-4fd5-94d9-4e4a6234a6ef"", ""expectedControlType"": ""Button"",    ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""Point"",                    ""type"": ""PassThrough"", ""id"": ""32b35790-4ed0-4e9a-aa41-69ac6d629449"", ""expectedControlType"": ""Vector2"",   ""processors"": """", ""interactions"": """", ""initialStateCheck"": true },
                { ""name"": ""Click"",                    ""type"": ""PassThrough"", ""id"": ""3c7022bf-7922-4f7c-a998-c437916075ad"", ""expectedControlType"": ""Button"",    ""processors"": """", ""interactions"": """", ""initialStateCheck"": true },
                { ""name"": ""ScrollWheel"",              ""type"": ""PassThrough"", ""id"": ""0489e84a-4833-4c40-bfae-cea84b696689"", ""expectedControlType"": ""Vector2"",   ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""MiddleClick"",              ""type"": ""PassThrough"", ""id"": ""dad70c86-b58c-4b17-88ad-f5e53adf419e"", ""expectedControlType"": ""Button"",    ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""RightClick"",               ""type"": ""PassThrough"", ""id"": ""44b200b1-1557-4083-816c-b22cbdf77ddf"", ""expectedControlType"": ""Button"",    ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""TrackedDevicePosition"",    ""type"": ""PassThrough"", ""id"": ""24908448-c609-4bc3-a128-ea258674378a"", ""expectedControlType"": ""Vector3"",   ""processors"": """", ""interactions"": """", ""initialStateCheck"": false },
                { ""name"": ""TrackedDeviceOrientation"", ""type"": ""PassThrough"", ""id"": ""9caa3d8a-6b2f-4e8e-8bad-6ede561bd9be"", ""expectedControlType"": ""Quaternion"",""processors"": """", ""interactions"": """", ""initialStateCheck"": false }
            ],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": [
        { ""name"": ""Keyboard&Mouse"", ""restrictToSuppliedDevices"": false, ""bindingGroup"": ""Keyboard&Mouse"", ""devices"": [ { ""devicePath"": ""<Keyboard>"", ""isOptional"": false, ""isOR"": false }, { ""devicePath"": ""<Mouse>"", ""isOptional"": false, ""isOR"": false } ] },
        { ""name"": ""Gamepad"",        ""restrictToSuppliedDevices"": false, ""bindingGroup"": ""Gamepad"",        ""devices"": [ { ""devicePath"": ""<Gamepad>"", ""isOptional"": false, ""isOR"": false } ] }
    ]
}";
    }
}
